package com.forager.app.map

import android.content.Context
import com.forager.app.data.local.OfflineRegionDao
import com.forager.app.data.local.OfflineRegionEntity
import com.forager.app.data.repository.runCatchingCancellable
import com.forager.app.domain.GeoDistance
import com.forager.app.domain.OfflineMapRepository
import com.forager.app.domain.OfflineRegionSummary
import com.forager.app.domain.model.LatLng
import com.forager.app.domain.model.Region
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
import kotlinx.coroutines.suspendCancellableCoroutine
import org.maplibre.android.MapLibre
import org.maplibre.android.geometry.LatLngBounds
import org.maplibre.android.offline.OfflineManager
import org.maplibre.android.offline.OfflineRegion
import org.maplibre.android.offline.OfflineRegionError
import org.maplibre.android.offline.OfflineRegionStatus
import org.maplibre.android.offline.OfflineTilePyramidRegionDefinition

/**
 * [OfflineMapRepository] backed by MapLibre's own `OfflineManager`, downloading real OSM-derived
 * vector tiles from the live Cloudflare Worker `docs/plans/pmtiles-worker-android-wiring.md`
 * describes.
 *
 * ## Many regions, one index
 *
 * This class used to model "the one downloaded region": `download()` deleted everything already on
 * disk first, and `getStatus()` answered a single nullable info. Per
 * `docs/plans/journal-trips-and-offline-regions.md`'s "Region management" section, it now manages
 * many: [download] adds a region, [deleteRegion] removes one, [listRegions] answers all of them.
 * [offlineRegionDao] is the index this needs and `OfflineManager`'s own opaque region list can't
 * provide on its own (see [com.forager.app.data.local.OfflineRegionEntity]'s doc comment for why the
 * Room table is the source of truth and the region's own metadata blob is the recovery copy, not
 * the other way around).
 *
 * Every `OfflineRegion`'s native [OfflineRegion.getId] doubles as this app's own region id — see
 * [OfflineRegionEntity]'s doc comment for why that's reused rather than inventing a second id.
 *
 * ## Why no hand-rolled tile writer this time
 *
 * `OfflineManager` owns a real embedded database (`OfflineRegion`s survive an app restart on their
 * own, confirmed on hardware by PR #23) and reports live tile/byte counts via
 * [OfflineRegion.getStatus] — nothing here re-derives or re-stores that. The only things
 * `OfflineManager`'s own store doesn't know are this region's user-facing name and zoom range, so
 * those, plus a redundant copy of centre/radius/created-at, are what [RegionMetadata] carries in the
 * `OfflineRegion`'s own opaque metadata bytes.
 *
 * ## Offline downloads use the label-stripped style, not the one a live map would render
 *
 * [OFFLINE_STYLE_URL] is served by the Cloudflare Worker at `/style/offline.json` — generated by
 * Protomaps' own `@protomaps/basemaps` `layers()` function with no `lang` option, which per that
 * package's `src/index.ts` takes only the `nolabels_layers()` branch: real geometry (roads, water,
 * landuse, buildings), zero `text-field`/glyph layers. This is not a stripped-down placeholder; it
 * is the same reference layer set a live labeled style would use, minus exactly the label layers.
 * That specific omission is load-bearing, not cosmetic: PR #23 confirmed on real hardware, with a
 * clean three-way isolation, that `OfflineManager` downloads of a style with glyph/`text-field`
 * layers crash the whole app natively during resource-list construction, regardless of region size,
 * while the identical vector source and geometry layers with glyphs removed download cleanly. See
 * `docs/plans/maplibre-migration.md` §7 and PR #23's description for the isolation evidence. A
 * future live-rendering basemap can use the full labeled style this same generator produces
 * (`forager_pmtiles_style.json`, generated but not yet bundled — see
 * `docs/plans/pmtiles-worker-android-wiring.md` step 1/2); offline downloads must not.
 *
 * [OFFLINE_STYLE_URL] is a real HTTPS URL, not `asset://forager_pmtiles_offline_style.json` (the
 * first attempt at this class) — hardware testing found that hangs `OfflineTilePyramidRegionDefinition`
 * at `completed=0/1` forever, the exact `asset://`-doesn't-resolve-through-OfflineManager stall PR
 * #23 already isolated for a different style. The style is now served by the same Worker the tiles
 * come from (`server/pmtiles-worker/src/index.ts`), keeping the dependency under this project's own
 * domain instead of `asset://` (broken here) or `raw.githubusercontent.com` (PR #23's throwaway
 * test-only approach).
 *
 * ## Verified against the pinned `org.maplibre.gl:android-sdk:13.5.0` artifact
 *
 * Every method called below (`OfflineManager.listOfflineRegions`/`createOfflineRegion`/
 * `setOfflineMapboxTileCountLimit`, `OfflineRegion.getId`/`setObserver`/`setDownloadState`/
 * `getStatus`/`delete`/`updateMetadata`, and the exact callback interface shapes) was checked with
 * `javap` against that artifact's `classes.jar` rather than assumed from documentation, the same
 * discipline this class's history always used. Not verified, and impossible to from this sandbox:
 * hardware behavior of overlapping regions and of a region rebuilt from its metadata blob after its
 * Room row is deliberately dropped.
 */
class MapLibreOfflineMapRepository(
    context: Context,
    private val offlineRegionDao: OfflineRegionDao,
) : OfflineMapRepository {

    private val appContext = context.applicationContext

    override suspend fun download(
        name: String,
        region: Region,
        onProgress: (downloaded: Int, total: Int) -> Unit,
    ): Result<OfflineRegionSummary> = runCatchingCancellable {
        val definition = OfflineTilePyramidRegionDefinition(
            OFFLINE_STYLE_URL,
            region.toLatLngBounds(),
            OfflineMapRepository.MIN_ZOOM,
            OfflineMapRepository.MAX_ZOOM,
            appContext.resources.displayMetrics.density,
        )
        // A placeholder timestamp, overwritten by updateMetadataSuspend below once the download
        // actually finishes — see this class's doc comment on why "downloaded at" means completion
        // time, matching this class's own original single-region semantics.
        val placeholderMetadata = RegionMetadata(name, region, OfflineMapRepository.MIN_ZOOM, OfflineMapRepository.MAX_ZOOM, downloadedAtEpochMillis = 0L).toBytes()

        val offlineRegion = offlineManager().createOfflineRegionSuspend(definition, placeholderMetadata)
        val finalStatus = try {
            offlineRegion.downloadToCompletionSuspend(onProgress)
        } catch (e: Exception) {
            // Never leave a half-downloaded region looking like a complete one.
            offlineRegion.deleteSuspend()
            throw e
        }

        val downloadedAt = downloadedAtEpochMillisProvider()
        offlineRegion.updateMetadataSuspend(RegionMetadata(name, region, OfflineMapRepository.MIN_ZOOM, OfflineMapRepository.MAX_ZOOM, downloadedAt).toBytes())
        offlineRegionDao.upsert(
            OfflineRegionEntity(
                id = offlineRegion.id,
                name = name,
                lat = region.lat,
                lng = region.lng,
                radiusKm = region.radiusKm,
                minZoom = OfflineMapRepository.MIN_ZOOM,
                maxZoom = OfflineMapRepository.MAX_ZOOM,
                createdAtEpochMillis = downloadedAt,
            ),
        )

        OfflineRegionSummary(
            id = offlineRegion.id,
            name = name,
            region = region,
            minZoom = OfflineMapRepository.MIN_ZOOM,
            maxZoom = OfflineMapRepository.MAX_ZOOM,
            tileCount = finalStatus.completedTileCount.toInt(),
            sizeBytes = finalStatus.completedResourceSize,
            createdAtEpochMillis = downloadedAt,
        )
    }

    override suspend fun deleteRegion(id: Long): Result<Unit> = runCatchingCancellable {
        offlineManager().listOfflineRegionsSuspend().firstOrNull { it.id == id }?.deleteSuspend()
        offlineRegionDao.deleteById(id)
    }

    override suspend fun listRegions(): Result<List<OfflineRegionSummary>> = runCatchingCancellable {
        val offlineRegions = offlineManager().listOfflineRegionsSuspend()
        val liveIds = offlineRegions.map { it.id }.toSet()

        // A Room row whose OfflineManager-backed region is simply gone (deleted by something other
        // than deleteRegion, e.g. OfflineManager's own database being reset) describes a download
        // that no longer exists — pruned rather than kept as a phantom entry with no real tiles
        // behind it.
        offlineRegionDao.getAll().filter { it.id !in liveIds }.forEach { offlineRegionDao.deleteById(it.id) }

        offlineRegions.mapNotNull { offlineRegion ->
            val status = offlineRegion.getStatusSuspend()

            // A region OfflineManager still has on file but never finished — e.g. the process was
            // killed mid-download — is the same "half-downloaded region looking complete" case
            // download()'s own catch block prevents within one run. A restart bypasses that catch
            // block entirely, so the same invariant is re-checked here, per region.
            if (!status.isComplete) {
                offlineRegion.deleteSuspend()
                offlineRegionDao.deleteById(offlineRegion.id)
                return@mapNotNull null
            }

            val row = offlineRegionDao.getById(offlineRegion.id)
                ?: offlineRegion.metadata.toRegionMetadata()?.let { metadata ->
                    // The Room row is missing but the region's own metadata blob survived — rebuild
                    // the row from it rather than dropping a real, on-disk, tile-budget-consuming
                    // region from the list. See OfflineRegionEntity's doc comment.
                    OfflineRegionEntity(
                        id = offlineRegion.id,
                        name = metadata.name,
                        lat = metadata.region.lat,
                        lng = metadata.region.lng,
                        radiusKm = metadata.region.radiusKm,
                        minZoom = metadata.minZoom,
                        maxZoom = metadata.maxZoom,
                        createdAtEpochMillis = metadata.downloadedAtEpochMillis,
                    ).also { offlineRegionDao.upsert(it) }
                }
                // Neither the table nor the blob can say what this region is — nothing usable to show.
                ?: return@mapNotNull null

            OfflineRegionSummary(
                id = row.id,
                name = row.name,
                region = Region(row.lat, row.lng, row.radiusKm),
                minZoom = row.minZoom,
                maxZoom = row.maxZoom,
                tileCount = status.completedTileCount.toInt(),
                sizeBytes = status.completedResourceSize,
                createdAtEpochMillis = row.createdAtEpochMillis,
            )
        }
    }

    // MapLibre.getInstance() must run before any other MapLibre API call touches the native
    // library — centralized here so every entry point (download/deleteRegion/listRegions, all of
    // which call this) gets it, rather than each call site needing to remember to.
    //
    // setOfflineMapboxTileCountLimit is likewise applied on every call rather than once at startup:
    // it's a cheap, idempotent native call with no callback and no getter (verified via javap — see
    // this class's doc comment), so there is no state to avoid re-setting, and this guarantees the
    // deliberate budget is in force before any offline operation regardless of call order.
    private fun offlineManager(): OfflineManager {
        ensureMapLibreStorageOutsideCache(appContext)
        MapLibre.getInstance(appContext)
        val manager = OfflineManager.getInstance(appContext)
        manager.setOfflineMapboxTileCountLimit(OfflineMapRepository.TILE_COUNT_LIMIT)
        return manager
    }

    /** `System.currentTimeMillis()` behind a seam only so a test could fake it; nothing here does yet. */
    private fun downloadedAtEpochMillisProvider(): Long = System.currentTimeMillis()
}

/**
 * The style `OfflineTilePyramidRegionDefinition` downloads — see this file's class doc comment for
 * why it must be the glyph-stripped variant, and for why this is a real HTTPS URL rather than
 * `asset://forager_pmtiles_offline_style.json`. (That was this class's first attempt, on the theory
 * that `asset://` is a plain sequential-read scheme unrelated to the `pmtiles://asset://`
 * byte-range-read limitation PR #23's doc comment names — a reasonable-sounding distinction that
 * hardware testing proved doesn't hold: `OfflineManager`'s resource-discovery path hung at
 * `completed=0/1` against it regardless, the exact same stall class, for a reason that specific
 * theory didn't predict. Recorded here so the theory doesn't get re-tried.)
 */
private const val OFFLINE_STYLE_URL = "https://forager-pmtiles.brandonlee1-894.workers.dev/style/offline.json"

private fun Region.toLatLngBounds(): LatLngBounds {
    val box = GeoDistance.boundingBox(LatLng(lat, lng), radiusKm)
    return LatLngBounds.Builder()
        .include(org.maplibre.android.geometry.LatLng(box.north, box.east))
        .include(org.maplibre.android.geometry.LatLng(box.south, box.west))
        .build()
}

// --- OfflineManager/OfflineRegion callback bridging -------------------------------------------
//
// Every callback shape below (which method is terminal, what each parameter means) was read off
// the pinned artifact's classes.jar with javap, not guessed from documentation — see this file's
// class doc comment.

private suspend fun OfflineManager.listOfflineRegionsSuspend(): List<OfflineRegion> =
    suspendCancellableCoroutine { continuation ->
        listOfflineRegions(object : OfflineManager.ListOfflineRegionsCallback {
            override fun onList(offlineRegions: Array<OfflineRegion>?) {
                if (continuation.isActive) continuation.resume(offlineRegions?.toList().orEmpty())
            }

            override fun onError(error: String) {
                if (continuation.isActive) continuation.resumeWithException(java.io.IOException(error))
            }
        })
    }

private suspend fun OfflineManager.createOfflineRegionSuspend(
    definition: OfflineTilePyramidRegionDefinition,
    metadata: ByteArray,
): OfflineRegion = suspendCancellableCoroutine { continuation ->
    createOfflineRegion(
        definition,
        metadata,
        object : OfflineManager.CreateOfflineRegionCallback {
            override fun onCreate(offlineRegion: OfflineRegion) {
                if (continuation.isActive) continuation.resume(offlineRegion)
            }

            override fun onError(error: String) {
                if (continuation.isActive) continuation.resumeWithException(java.io.IOException(error))
            }
        },
    )
}

/**
 * Sets an observer and activates the download, suspending until [OfflineRegionStatus.isComplete]
 * or a terminal error — mirroring exactly the observer/state-machine shape PR #23's
 * `MapLibreBasemapPreviewActivity` proved on hardware (`setObserver` then
 * `setDownloadState(STATE_ACTIVE)`, [onProgress] driven by every `onStatusChanged`), just bridged
 * into a suspend function instead of Compose state.
 */
private suspend fun OfflineRegion.downloadToCompletionSuspend(
    onProgress: (downloaded: Int, total: Int) -> Unit,
): OfflineRegionStatus = suspendCancellableCoroutine { continuation ->
    setObserver(object : OfflineRegion.OfflineRegionObserver {
        override fun onStatusChanged(status: OfflineRegionStatus) {
            onProgress(status.completedResourceCount.toInt(), status.requiredResourceCount.toInt())
            if (status.isComplete && continuation.isActive) continuation.resume(status)
        }

        override fun onError(error: OfflineRegionError) {
            if (continuation.isActive) {
                continuation.resumeWithException(java.io.IOException("${error.reason}: ${error.message}"))
            }
        }

        override fun mapboxTileCountLimitExceeded(limit: Long) {
            if (continuation.isActive) {
                continuation.resumeWithException(java.io.IOException("Offline tile count limit exceeded ($limit)."))
            }
        }
    })
    setDownloadState(OfflineRegion.STATE_ACTIVE)
}

private suspend fun OfflineRegion.getStatusSuspend(): OfflineRegionStatus =
    suspendCancellableCoroutine { continuation ->
        getStatus(object : OfflineRegion.OfflineRegionStatusCallback {
            override fun onStatus(status: OfflineRegionStatus?) {
                if (!continuation.isActive) return
                if (status != null) continuation.resume(status) else continuation.resumeWithException(java.io.IOException("getStatus returned no status."))
            }

            override fun onError(error: String?) {
                if (continuation.isActive) continuation.resumeWithException(java.io.IOException(error ?: "Unknown offline region status error."))
            }
        })
    }

private suspend fun OfflineRegion.deleteSuspend(): Unit = suspendCancellableCoroutine { continuation ->
    delete(object : OfflineRegion.OfflineRegionDeleteCallback {
        override fun onDelete() {
            if (continuation.isActive) continuation.resume(Unit)
        }

        override fun onError(error: String) {
            if (continuation.isActive) continuation.resumeWithException(java.io.IOException(error))
        }
    })
}

private suspend fun OfflineRegion.updateMetadataSuspend(metadata: ByteArray): Unit =
    suspendCancellableCoroutine { continuation ->
        updateMetadata(
            metadata,
            object : OfflineRegion.OfflineRegionUpdateMetadataCallback {
                override fun onUpdate(metadata: ByteArray) {
                    if (continuation.isActive) continuation.resume(Unit)
                }

                override fun onError(error: String) {
                    if (continuation.isActive) continuation.resumeWithException(java.io.IOException(error))
                }
            },
        )
    }
