package com.forager.app.map

import android.content.Context
import com.forager.app.data.repository.runCatchingCancellable
import com.forager.app.domain.GeoDistance
import com.forager.app.domain.OfflineMapInfo
import com.forager.app.domain.OfflineMapRepository
import com.forager.app.domain.model.LatLng
import com.forager.app.domain.model.Region
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
import kotlinx.coroutines.suspendCancellableCoroutine
import org.maplibre.android.MapLibre
import org.maplibre.android.geometry.LatLngBounds
import org.maplibre.android.offline.OfflineManager
import org.maplibre.android.offline.OfflineRegion
import org.maplibre.android.offline.OfflineRegionError
import org.maplibre.android.offline.OfflineRegionStatus
import org.maplibre.android.offline.OfflineTilePyramidRegionDefinition

/**
 * [OfflineMapRepository] backed by MapLibre's own `OfflineManager`, downloading real OSM-derived
 * vector tiles from the live Cloudflare Worker `docs/plans/pmtiles-worker-android-wiring.md`
 * describes — replacing `OsmdroidOfflineMapRepository`'s USGS-only raster downloader per the owner's
 * decision to switch offline downloads to the PMTiles vector source (see that doc's "Open decisions").
 *
 * ## Why no hand-rolled tile writer this time
 *
 * `OsmdroidOfflineMapRepository` needed [PersistentTileWriter] and a sidecar status file because
 * osmdroid's `CacheManager` has no persistence story of its own beyond a caller-supplied
 * `IFilesystemCache`. `OfflineManager` is the opposite: it owns a real embedded database
 * (`OfflineRegion`s survive an app restart on its own, confirmed on hardware by PR #23) and reports
 * live tile/byte counts via [OfflineRegion.getStatus] — nothing here re-derives or re-stores that.
 * The only thing `OfflineManager`'s own store *doesn't* know is which [Region] a download was for
 * (it only knows a [LatLngBounds]) and this app's own "when did this finish" timestamp, so those two
 * fields are all [RegionMetadata] carries, in the `OfflineRegion`'s own opaque metadata bytes.
 *
 * ## Offline downloads use the label-stripped style, not the one a live map would render
 *
 * [OFFLINE_STYLE_ASSET_URL] points at `forager_pmtiles_offline_style.json` — generated by
 * Protomaps' own `@protomaps/basemaps` `layers()` function with no `lang` option, which per that
 * package's `src/index.ts` takes only the `nolabels_layers()` branch: real geometry (roads, water,
 * landuse, buildings), zero `text-field`/glyph layers. This is not a stripped-down placeholder; it
 * is the same reference layer set a live labeled style would use, minus exactly the label layers.
 * That specific omission is load-bearing, not cosmetic: PR #23 confirmed on real hardware, with a
 * clean three-way isolation, that `OfflineManager` downloads of a style with glyph/`text-field`
 * layers crash the whole app natively during resource-list construction, regardless of region size,
 * while the identical vector source and geometry layers with glyphs removed download cleanly. See
 * `docs/plans/maplibre-migration.md` §7 and PR #23's description for the isolation evidence. A
 * future live-rendering basemap can use the full labeled style this same generator produces
 * (`forager_pmtiles_style.json`, generated but not yet bundled — see
 * `docs/plans/pmtiles-worker-android-wiring.md` step 1/2); offline downloads must not.
 *
 * ## Verified against the pinned `org.maplibre.gl:android-sdk:13.5.0` artifact
 *
 * Every method called below (`OfflineManager.listOfflineRegions`/`createOfflineRegion`,
 * `OfflineRegion.setObserver`/`setDownloadState`/`getStatus`/`delete`/`updateMetadata`, and the
 * exact callback interface shapes) was checked with `javap` against that artifact's `classes.jar`
 * rather than assumed from documentation, the same discipline `OsmdroidOfflineMapRepository`'s own
 * doc comment used for its pinned osmdroid artifact. Not verified, and impossible to from this
 * sandbox: hardware behavior of a *second* offline region replacing a first, or of this exact
 * asset-URL style being resolved by `OfflineTilePyramidRegionDefinition` — PR #23 confirmed the
 * mechanism against `raw.githubusercontent.com`-hosted style URLs, not an `asset://` one. Spot-check
 * on a real device before relying on this further.
 */
class MapLibreOfflineMapRepository(context: Context) : OfflineMapRepository {

    private val appContext = context.applicationContext

    override suspend fun download(
        region: Region,
        onProgress: (downloaded: Int, total: Int) -> Unit,
    ): Result<OfflineMapInfo> = runCatchingCancellable {
        MapLibre.getInstance(appContext)
        offlineManager().listOfflineRegionsSuspend().forEach { it.deleteSuspend() }

        val definition = OfflineTilePyramidRegionDefinition(
            OFFLINE_STYLE_ASSET_URL,
            region.toLatLngBounds(),
            OFFLINE_MIN_ZOOM,
            OFFLINE_MAX_ZOOM,
            appContext.resources.displayMetrics.density,
        )
        // A placeholder timestamp, overwritten by updateMetadataSuspend below once the download
        // actually finishes — see this class's doc comment on why "downloaded at" means completion
        // time, matching OsmdroidOfflineMapRepository's exact semantics, not creation time.
        val placeholderMetadata = RegionMetadata(region, downloadedAtEpochMillis = 0L).toBytes()

        val offlineRegion = offlineManager().createOfflineRegionSuspend(definition, placeholderMetadata)
        val finalStatus = try {
            offlineRegion.downloadToCompletionSuspend(onProgress)
        } catch (e: Exception) {
            // Never leave a half-downloaded region looking like a complete one — the same reasoning
            // OsmdroidOfflineMapRepository's download() catch block carries, applied to
            // OfflineManager's own store instead of a tiles directory this class doesn't own.
            offlineRegion.deleteSuspend()
            throw e
        }

        val downloadedAt = downloadedAtEpochMillisProvider()
        offlineRegion.updateMetadataSuspend(RegionMetadata(region, downloadedAt).toBytes())

        OfflineMapInfo(
            region = region,
            tileCount = finalStatus.completedTileCount.toInt(),
            sizeBytes = finalStatus.completedResourceSize,
            downloadedAtEpochMillis = downloadedAt,
        )
    }

    override suspend fun delete(): Result<Unit> = runCatchingCancellable {
        offlineManager().listOfflineRegionsSuspend().forEach { it.deleteSuspend() }
    }

    override suspend fun getStatus(): Result<OfflineMapInfo?> = runCatchingCancellable {
        val region = offlineManager().listOfflineRegionsSuspend().firstOrNull()
            ?: return@runCatchingCancellable null
        val metadata = region.metadata.toRegionMetadata() ?: return@runCatchingCancellable null
        val status = region.getStatusSuspend()

        // A region OfflineManager still has on file but never finished — e.g. the process was
        // killed mid-download — is exactly the "half-downloaded region looking complete" case
        // download()'s own catch block prevents within one run. A restart bypasses that catch
        // block entirely, so the same invariant is re-checked here: an incomplete leftover reads
        // as nothing downloaded, and is cleaned up rather than left to keep confusing future reads.
        if (!status.isComplete) {
            region.deleteSuspend()
            return@runCatchingCancellable null
        }

        OfflineMapInfo(
            region = metadata.region,
            tileCount = status.completedTileCount.toInt(),
            sizeBytes = status.completedResourceSize,
            downloadedAtEpochMillis = metadata.downloadedAtEpochMillis,
        )
    }

    private fun offlineManager(): OfflineManager = OfflineManager.getInstance(appContext)

    /** `System.currentTimeMillis()` behind a seam only so a test could fake it; nothing here does yet. */
    private fun downloadedAtEpochMillisProvider(): Long = System.currentTimeMillis()
}

/**
 * The style `OfflineTilePyramidRegionDefinition` downloads — see this file's class doc comment for
 * why it must be the glyph-stripped variant. `asset://` is the same scheme MapLibre's own
 * `AssetFileSource` resolves for a style *JSON* read (a small sequential read); this is a different
 * case from the `pmtiles://asset://` limitation PR #23's doc comment names, which is specific to
 * PMTiles' byte-range tile reads, not whole-file style JSON.
 */
private const val OFFLINE_STYLE_ASSET_URL = "asset://forager_pmtiles_offline_style.json"

/**
 * The PMTiles archive this style's source ultimately reads from is built to zoom 14 (per PR #24's
 * description of the `us.pmtiles` archive) — [OFFLINE_MAX_ZOOM] stays at that ceiling rather than
 * requesting tiles the archive doesn't have. [OFFLINE_MIN_ZOOM] is an adjustable assumption, the
 * same kind `OsmdroidOfflineMapRepository.ZOOM_LEVELS_BELOW_MAX` was: a wider span means more usable
 * offline zoom range at the cost of more tiles, and this project has no usage data yet on what span
 * foraging trips actually need.
 */
private const val OFFLINE_MAX_ZOOM = 14.0
private const val OFFLINE_MIN_ZOOM = 10.0

private fun Region.toLatLngBounds(): LatLngBounds {
    val box = GeoDistance.boundingBox(LatLng(lat, lng), radiusKm)
    return LatLngBounds.Builder()
        .include(org.maplibre.android.geometry.LatLng(box.north, box.east))
        .include(org.maplibre.android.geometry.LatLng(box.south, box.west))
        .build()
}

// --- OfflineManager/OfflineRegion callback bridging -------------------------------------------
//
// Every callback shape below (which method is terminal, what each parameter means) was read off
// the pinned artifact's classes.jar with javap, not guessed from documentation — see this file's
// class doc comment.

private suspend fun OfflineManager.listOfflineRegionsSuspend(): List<OfflineRegion> =
    suspendCancellableCoroutine { continuation ->
        listOfflineRegions(object : OfflineManager.ListOfflineRegionsCallback {
            override fun onList(offlineRegions: Array<OfflineRegion>?) {
                if (continuation.isActive) continuation.resume(offlineRegions?.toList().orEmpty())
            }

            override fun onError(error: String) {
                if (continuation.isActive) continuation.resumeWithException(java.io.IOException(error))
            }
        })
    }

private suspend fun OfflineManager.createOfflineRegionSuspend(
    definition: OfflineTilePyramidRegionDefinition,
    metadata: ByteArray,
): OfflineRegion = suspendCancellableCoroutine { continuation ->
    createOfflineRegion(
        definition,
        metadata,
        object : OfflineManager.CreateOfflineRegionCallback {
            override fun onCreate(offlineRegion: OfflineRegion) {
                if (continuation.isActive) continuation.resume(offlineRegion)
            }

            override fun onError(error: String) {
                if (continuation.isActive) continuation.resumeWithException(java.io.IOException(error))
            }
        },
    )
}

/**
 * Sets an observer and activates the download, suspending until [OfflineRegionStatus.isComplete]
 * or a terminal error — mirroring exactly the observer/state-machine shape PR #23's
 * `MapLibreBasemapPreviewActivity` proved on hardware (`setObserver` then
 * `setDownloadState(STATE_ACTIVE)`, [onProgress] driven by every `onStatusChanged`), just bridged
 * into a suspend function instead of Compose state.
 */
private suspend fun OfflineRegion.downloadToCompletionSuspend(
    onProgress: (downloaded: Int, total: Int) -> Unit,
): OfflineRegionStatus = suspendCancellableCoroutine { continuation ->
    setObserver(object : OfflineRegion.OfflineRegionObserver {
        override fun onStatusChanged(status: OfflineRegionStatus) {
            onProgress(status.completedResourceCount.toInt(), status.requiredResourceCount.toInt())
            if (status.isComplete && continuation.isActive) continuation.resume(status)
        }

        override fun onError(error: OfflineRegionError) {
            if (continuation.isActive) {
                continuation.resumeWithException(java.io.IOException("${error.reason}: ${error.message}"))
            }
        }

        override fun mapboxTileCountLimitExceeded(limit: Long) {
            if (continuation.isActive) {
                continuation.resumeWithException(java.io.IOException("Offline tile count limit exceeded ($limit)."))
            }
        }
    })
    setDownloadState(OfflineRegion.STATE_ACTIVE)
}

private suspend fun OfflineRegion.getStatusSuspend(): OfflineRegionStatus =
    suspendCancellableCoroutine { continuation ->
        getStatus(object : OfflineRegion.OfflineRegionStatusCallback {
            override fun onStatus(status: OfflineRegionStatus?) {
                if (!continuation.isActive) return
                if (status != null) continuation.resume(status) else continuation.resumeWithException(java.io.IOException("getStatus returned no status."))
            }

            override fun onError(error: String?) {
                if (continuation.isActive) continuation.resumeWithException(java.io.IOException(error ?: "Unknown offline region status error."))
            }
        })
    }

private suspend fun OfflineRegion.deleteSuspend(): Unit = suspendCancellableCoroutine { continuation ->
    delete(object : OfflineRegion.OfflineRegionDeleteCallback {
        override fun onDelete() {
            if (continuation.isActive) continuation.resume(Unit)
        }

        override fun onError(error: String) {
            if (continuation.isActive) continuation.resumeWithException(java.io.IOException(error))
        }
    })
}

private suspend fun OfflineRegion.updateMetadataSuspend(metadata: ByteArray): Unit =
    suspendCancellableCoroutine { continuation ->
        updateMetadata(
            metadata,
            object : OfflineRegion.OfflineRegionUpdateMetadataCallback {
                override fun onUpdate(metadata: ByteArray) {
                    if (continuation.isActive) continuation.resume(Unit)
                }

                override fun onError(error: String) {
                    if (continuation.isActive) continuation.resumeWithException(java.io.IOException(error))
                }
            },
        )
    }
